//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebService02Cliente.BaldorWs {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceBaldorSoap", Namespace="http://tempuri.org/")]
    public partial class WebServiceBaldor : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SumaOperationCompleted;
        
        private System.Threading.SendOrPostCallback RestaOperationCompleted;
        
        private System.Threading.SendOrPostCallback MultiplicaOperationCompleted;
        
        private System.Threading.SendOrPostCallback DivideOperationCompleted;
        
        private System.Threading.SendOrPostCallback MinimoOperationCompleted;
        
        private System.Threading.SendOrPostCallback MaximoOperationCompleted;
        
        private System.Threading.SendOrPostCallback PromedioOperationCompleted;
        
        private System.Threading.SendOrPostCallback PorcentajeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebServiceBaldor() {
            this.Url = global::WebService02Cliente.Properties.Settings.Default.WebService02Cliente_BaldorWs_WebServiceBaldor;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SumaCompletedEventHandler SumaCompleted;
        
        /// <remarks/>
        public event RestaCompletedEventHandler RestaCompleted;
        
        /// <remarks/>
        public event MultiplicaCompletedEventHandler MultiplicaCompleted;
        
        /// <remarks/>
        public event DivideCompletedEventHandler DivideCompleted;
        
        /// <remarks/>
        public event MinimoCompletedEventHandler MinimoCompleted;
        
        /// <remarks/>
        public event MaximoCompletedEventHandler MaximoCompleted;
        
        /// <remarks/>
        public event PromedioCompletedEventHandler PromedioCompleted;
        
        /// <remarks/>
        public event PorcentajeCompletedEventHandler PorcentajeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Suma", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Suma(string[] v) {
            object[] results = this.Invoke("Suma", new object[] {
                        v});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SumaAsync(string[] v) {
            this.SumaAsync(v, null);
        }
        
        /// <remarks/>
        public void SumaAsync(string[] v, object userState) {
            if ((this.SumaOperationCompleted == null)) {
                this.SumaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSumaOperationCompleted);
            }
            this.InvokeAsync("Suma", new object[] {
                        v}, this.SumaOperationCompleted, userState);
        }
        
        private void OnSumaOperationCompleted(object arg) {
            if ((this.SumaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SumaCompleted(this, new SumaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Resta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Resta(string s1, string s2) {
            object[] results = this.Invoke("Resta", new object[] {
                        s1,
                        s2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RestaAsync(string s1, string s2) {
            this.RestaAsync(s1, s2, null);
        }
        
        /// <remarks/>
        public void RestaAsync(string s1, string s2, object userState) {
            if ((this.RestaOperationCompleted == null)) {
                this.RestaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRestaOperationCompleted);
            }
            this.InvokeAsync("Resta", new object[] {
                        s1,
                        s2}, this.RestaOperationCompleted, userState);
        }
        
        private void OnRestaOperationCompleted(object arg) {
            if ((this.RestaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RestaCompleted(this, new RestaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Multiplica", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Multiplica(string s1, string s2) {
            object[] results = this.Invoke("Multiplica", new object[] {
                        s1,
                        s2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MultiplicaAsync(string s1, string s2) {
            this.MultiplicaAsync(s1, s2, null);
        }
        
        /// <remarks/>
        public void MultiplicaAsync(string s1, string s2, object userState) {
            if ((this.MultiplicaOperationCompleted == null)) {
                this.MultiplicaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMultiplicaOperationCompleted);
            }
            this.InvokeAsync("Multiplica", new object[] {
                        s1,
                        s2}, this.MultiplicaOperationCompleted, userState);
        }
        
        private void OnMultiplicaOperationCompleted(object arg) {
            if ((this.MultiplicaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MultiplicaCompleted(this, new MultiplicaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Divide", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Divide(string s1, string s2) {
            object[] results = this.Invoke("Divide", new object[] {
                        s1,
                        s2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DivideAsync(string s1, string s2) {
            this.DivideAsync(s1, s2, null);
        }
        
        /// <remarks/>
        public void DivideAsync(string s1, string s2, object userState) {
            if ((this.DivideOperationCompleted == null)) {
                this.DivideOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDivideOperationCompleted);
            }
            this.InvokeAsync("Divide", new object[] {
                        s1,
                        s2}, this.DivideOperationCompleted, userState);
        }
        
        private void OnDivideOperationCompleted(object arg) {
            if ((this.DivideCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DivideCompleted(this, new DivideCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Minimo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Minimo(string[] v) {
            object[] results = this.Invoke("Minimo", new object[] {
                        v});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MinimoAsync(string[] v) {
            this.MinimoAsync(v, null);
        }
        
        /// <remarks/>
        public void MinimoAsync(string[] v, object userState) {
            if ((this.MinimoOperationCompleted == null)) {
                this.MinimoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMinimoOperationCompleted);
            }
            this.InvokeAsync("Minimo", new object[] {
                        v}, this.MinimoOperationCompleted, userState);
        }
        
        private void OnMinimoOperationCompleted(object arg) {
            if ((this.MinimoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MinimoCompleted(this, new MinimoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Maximo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Maximo(string[] v) {
            object[] results = this.Invoke("Maximo", new object[] {
                        v});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MaximoAsync(string[] v) {
            this.MaximoAsync(v, null);
        }
        
        /// <remarks/>
        public void MaximoAsync(string[] v, object userState) {
            if ((this.MaximoOperationCompleted == null)) {
                this.MaximoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMaximoOperationCompleted);
            }
            this.InvokeAsync("Maximo", new object[] {
                        v}, this.MaximoOperationCompleted, userState);
        }
        
        private void OnMaximoOperationCompleted(object arg) {
            if ((this.MaximoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MaximoCompleted(this, new MaximoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Promedio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Promedio(string[] v) {
            object[] results = this.Invoke("Promedio", new object[] {
                        v});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PromedioAsync(string[] v) {
            this.PromedioAsync(v, null);
        }
        
        /// <remarks/>
        public void PromedioAsync(string[] v, object userState) {
            if ((this.PromedioOperationCompleted == null)) {
                this.PromedioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPromedioOperationCompleted);
            }
            this.InvokeAsync("Promedio", new object[] {
                        v}, this.PromedioOperationCompleted, userState);
        }
        
        private void OnPromedioOperationCompleted(object arg) {
            if ((this.PromedioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PromedioCompleted(this, new PromedioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Porcentaje", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Porcentaje(string s1, string s2) {
            object[] results = this.Invoke("Porcentaje", new object[] {
                        s1,
                        s2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PorcentajeAsync(string s1, string s2) {
            this.PorcentajeAsync(s1, s2, null);
        }
        
        /// <remarks/>
        public void PorcentajeAsync(string s1, string s2, object userState) {
            if ((this.PorcentajeOperationCompleted == null)) {
                this.PorcentajeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPorcentajeOperationCompleted);
            }
            this.InvokeAsync("Porcentaje", new object[] {
                        s1,
                        s2}, this.PorcentajeOperationCompleted, userState);
        }
        
        private void OnPorcentajeOperationCompleted(object arg) {
            if ((this.PorcentajeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PorcentajeCompleted(this, new PorcentajeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SumaCompletedEventHandler(object sender, SumaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SumaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SumaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void RestaCompletedEventHandler(object sender, RestaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RestaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RestaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void MultiplicaCompletedEventHandler(object sender, MultiplicaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MultiplicaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MultiplicaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void DivideCompletedEventHandler(object sender, DivideCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DivideCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DivideCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void MinimoCompletedEventHandler(object sender, MinimoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MinimoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MinimoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void MaximoCompletedEventHandler(object sender, MaximoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MaximoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MaximoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void PromedioCompletedEventHandler(object sender, PromedioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PromedioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PromedioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void PorcentajeCompletedEventHandler(object sender, PorcentajeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PorcentajeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PorcentajeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591